### ISSUE TITLE
Remove 4 corners logic

### ISSUE THREAD

**Issue by EmilieDel** [BlueBrain/Atlas-Download-Tools#27]
Currently we check the 4 corners value to decide on the image_id. We should directly
- take the one given by the metadata
- using this 4 corners logic as a sanity check raising an Exception when it is not the one in the majority of the corners

**Comment by jankrepl** [comment]
IMO this would make the code way simpler and faster!

Without sanity checking the pipeline would then simply be (for a fixed coronal image):
* determine a single `p` (using `xy_to_pir` where the `x, y` could be the center of the image)`
* Apply 3D transform on `(p * np.ones(), i_grid, r_grid)`
* Apply 2D transform
